title: "Henrique Vaz"
author: "Henrique Porto Vaz"
description: "Computer Engineering student at MSU | Multilingual | App Developer | Strategic Thinker"

navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Contact: "contact"

avatar: "/assets/img/avatar-icon.png"
round-avatar: true

social-network-links:
  email: "henriqueportovaz2005@gmail.com"
  github: HenriquePVaz
  linkedin: Henrique Porto Vaz
  twitter: "@hnrkk_"
  instagram: henriquepvazz
  whatsapp: "+1 (248) 590-1202"

rss-description: "Personal portfolio of Henrique Porto Vaz, Computer Engineering student and future innovator."
url-pretty: "HenriquePVaz.github.io"
title-on-all-pages: true

share-links-active:
  twitter: true
  facebook: false
  linkedin: true

page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

post_search: true
edit_page_button: false

timezone: "Eastern Time (US & Canada)"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-paginate
  - jekyll-sitemap
