# --------------------------
# Personal Portfolio Config
# --------------------------

title: "Henrique Vaz"
author: "Henrique Porto Vaz"
description: "Computer Science student at MSU | Future Engineer | Problem Solver"

# --- Navigation Bar ---
navbar-links:
  About Me: "aboutme"
  Projects: "projects"
  Contact: "contact"

# --- Avatar (Top of Site) ---
avatar: "/assets/img/avatar-icon.png"
round-avatar: true

# --- Footer Social Media Links ---
social-network-links:
  email: "henriqueportovaz2005@gmail.com"
  github: HenriquePVaz
  linkedin: Henrique Porto Vaz
  twitter: "@hnrkk_"
  instagram: henriquepvazz
  whatsapp: "+1 (248) 590-1202"

# --- SEO / Sharing ---
rss-description: "Personal website and portfolio of Henrique Vaz"
url-pretty: "HenriquePVaz.github.io"
title-on-all-pages: true

# --- Social Share Buttons ---
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

# --- Color Theme (Optional) ---
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
navbar-border-col: "#DDDDDD"
footer-col: "#EAEAEA"
footer-text-col: "#777777"
footer-link-col: "#404040"
footer-hover-col: "#0085A1"

# --- Search & Edit ---
post_search: true
edit_page_button: false

# --- Build Settings ---
timezone: "Eastern Time (US & Canada)"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# --- Page Defaults ---
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
  - scope:
      path: ""
    values:
      layout: "page"

# --- Exclude Files from Build ---
exclude:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - Gemfile
  - Gemfile.lock

# --- Plugins ---
plugins:
  - jekyll-paginate
  - jekyll-sitemap


